# ----------------------------------------
# File: yazi.toml
# Description: Yazi file manager configuration
# ----------------------------------------

[manager]
ratio = [1, 4, 3]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
